name: "Auto Close/Open Issues"
description: "Close or reopen issues when they are moved to a specific column"
author: "pamasse"
inputs:
  owner:
    description: The account name of the GitHub organization.
    required: true
  github-token:
    description: Personal access token or an OAuth token. the write:org scope is required for read-write access.
    required: true
  project-id:
    description: Project number as you see it in the URL of the project.
    required: true
  open-issue-columns:
    description: "Reopen issues that are moved to these project columns, value must be a comma separated list of project columns"
    default: ""
    required: true
  closed-issue-columns:
    description: "Close issues that are moved to these project columns, value must be a comma separated list of project columns"
    default: "Closed, Done"
    required: true
outputs:
  issues:
    description: "Issues that have been either closed or reopened, value is a JSON string"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "box"
  color: "red"
