name: Test workflow

#on:
#  schedule:
#    - cron: "0 5 * * 1"

jobs:
  test:
    name: Basic Run Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run
        uses: ./
        with:
          owner: Vestack
          project-id: 1
          github-token: ${{ secrets.PROJECT_PAT }}
          closed-issue-columns: Done
          open-issue-columns: Bugs,To Do,In Progress,To Review
